bstatePath: .yarn/build-state.yml

cacheFolder: .yarn/cache

compressionLevel: 9

enableAbsoluteVirtuals: true

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableImmutableCache: true

enableImmutableInstalls: true

enableMirror: true

enableNetwork: true

enableProgressBars: true

enableScripts: true

enableStrictSsl: true

enableTelemetry: false

enableTimers: true

globalFolder: .yarn/global

httpRetry: 4

httpTimeout: 10000

ignoreCwd: false

ignorePath: false

initFields:
  version: 0.0.1
  author: Cris Mihalache <xf3rno@pm.me>
  license: MIT
  private: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: private

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpDataPath: .yarn/pnp.data.json

pnpMode: loose

preferInteractive: true

progressBarStyle: simba

virtualFolder: .yarn/$$virtual

yarnPath: .yarn/releases/yarn-2.4.0.cjs
